// Author: Reynaldo Belfort Pierrilus, Computer Engineering Undergraduate
// University of Puerto Rico - Mayagüez

export default  {
    "FilePaths": [
       "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_1_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_3_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_2_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_4_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_5_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_6_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_7_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_8_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_9_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_10_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_11_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_12_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_13_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_14_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_15_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_16_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_17_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_18_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_19_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_20_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_21_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_22_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_23_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_24_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_25_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_26_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_27_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_28_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_29_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_30_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_31_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_32_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_33_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_34_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_35_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_36_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_37_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_38_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_39_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_40_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_41_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_42_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_43_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_44_RCM.png",
        "C:\\Users\\reyna\\Google Drive\\UPRM\\Capstone Project\\- Project - Dermatologists Assistive Tool (DermAT) - Prof. Heidy\\RCM_Data\\Training_Testing\\Testing\\Dark9_RCMpng_Test\\Dark9_45_RCM.png",
        ],
}